name: 'Tiny Tapeout FPGA bitstream (iCE40 UP5K)'
description: 'Generate an iCE40 UP5K FPGA bitstream from your Tiny Tapeout project'

branding:
  color: purple
  icon: check

inputs:
  tools-repo:
    description: 'Override tt-support-tools repository with iCE40 UP5K support'
    # Default is expected to be <owner>/<repo>
    default: 'ulx3s/tt-support-tools'
    required: false

  tools-ref:
    description: 'Override tt-support-tools branch/tag/commit'
  # default: 'main'
    default: 'experimental' # TODO remove and uncomment above ^
    required: false

  breakout-target:
    description: 'iCE40 UP5K breakout target (classic, fabricfox)'
    default: 'fabricfox'
    required: false

  artifact-name:
    description: 'Artifact base name'
    default: 'fpga_ice40_up5k'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout tt-support-tools repo
      uses: actions/checkout@v6
      with:
        repository: "${{ inputs.tools-repo }}"
        path: tt
        ref: "${{ inputs.tools-ref }}"

    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'
        cache: 'pip' # caching pip dependencies

    - name: Install tt-support-tools dependencies
      shell: bash
      run: pip install -r tt/requirements.txt

    - name: Install Python packages
      if: ${{ hashFiles('test/requirements.txt') != '' }}
      shell: bash
      run: pip install -r test/requirements.txt

    - name: Fetch verilog and build config
      shell: bash
      run: |
        python tt/tt_tool.py --create-user-config $FLOW_ARG

    - name: Install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v4
      with:
        python-override: true
        version: '2026-04-26'

    - name: Create iCE40 UP5K bitstream
      shell: bash
      run: |
        echo "Building iCE40 UP5K (${{ inputs.breakout-target }})"

        python tt/tt_fpga.py harden \
            --name tt_um_fpga_ice40up5k \
            --breakout-target ${{ inputs.breakout-target }}

    - name: Upload iCE40 UP5K bitstream
      if: always()
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          build/*
          docs/*
          src/*
          info.yaml
          LICENSE
